# Name plugin "GoldBlock"
# Version 0.1.7.1
# Discord https://discord.gg/ZhfY2tKgxR

message:

  # Сообщение о спавне золотого блока
  posMessage: '&eКоординаты золотого блока x: %s y: %s z: %s'

  # Сообщение по окончанию золотого блока
  endMessage: "&bЗолотой блок закончился"

  # Сообщение при получение денег
  youReceived: "&6&lВы получили: &a%s&6&l$"

  startMessage: "&e&lДо золотого блока: %s"

  # Сколько будет награда за золотой блок (награда делится на всех кто находится возле золотого блока)
count: 100

  # Выбрать какая экономика будет использоваться (Vault, PlayerPoint)
economy: Vault

# Радиус где может появиться золотой блок
radius:
  x: 2000
  z: 2000

# Центр поиска золотого блока (если center = 100 то радиус поиска будет от -1900 до 2100)
center:
  x: 0
  z: 0

# Сколько времени будет идти золотой блок (время указывать в секундах 300 = 5 мин)
timeGoldBlock: 300

# На каком расстояние от золотого блока игрок будет получать деньги
radiusPay: 5

# Какой тип блока будет использоваться
materialGoldBlock: GOLD_BLOCK

# На каких блоках может появиться золотой блок
materialList:
  - GRASS_BLOCK
  - SAND

# Задержка между золотыми блоками (время указывать в секундах 1800 = 30 мин)
time: 1800

# Текст голограммы
hologramLines:
  - "&6&lЗолотой блок"
  - "{endtime}"

# Установить позицию голограммы
hologramOffset:
  x: 0.5
  y: 1.7
  z: 0.5

# Когда выводить сообщение когда будет золотой блок (ниже указан пример)
reportMessage:
  - 1800 # До золотого блока 00:30:00
  - 600 # До золотого блока 00:10:00
  - 300 # До золотого блока 00:05:00
  - 240
  - 180
  - 120
  - 60
  - 30
  - 10
  - 5
  - 4
  - 3
  - 2
  - 1



