# Name plugin "GoldBlock"
# Version 0.2
# Discord https://discord.gg/ZhfY2tKgxR

GoldBlocks:
  # Название вашего золотого блока
  default:
    type: default
    # Мир в котором появляется золотой блок
    world: 'world'
    # Выбрать какая экономика будет использоваться (Vault, PlayerPoint)
    economy: 'Vault'
    # Выбрать будет ли золотой блок появляться рандомно или в определённом месте
    blockMovementType: 'static' # (static - золотой блок будет появляться в определённом месте,
                         #random - появляется в радиусе от центра поиска золотого блока)
    # Радиус где может появиться золотой блок
    radius: 2000
    # Максимальная и минимальная высота на которой может появиться золотой блок
    height:
      max: 90
      min: 50
    # Центр поиска золотого блока (если center = 0 то радиус поиска будет от -2000 до 2000)
    center:
      x: 0
      z: 0
    # Позиция золотого блока для static
    posGoldBlock:
      x: 0
      y: 0
      z: 0
    # Сколько времени будет идти золотой блок (время указывать в секундах 300 = 5 мин)
    timeGoldBlock: 300
    # Сколько должно быть игроков на сервере чтобы золотой блок начался
    minPlayers: 1
    # Сколько будет награда за золотой блок
    count: 100
    # Будет ли делиться награда между игроками или нет
    shareCount: true
    # На каком расстоянии от золотого блока игрок будет получать деньги
    radiusPay: 5
    # Какой тип блока будет использоваться
    materialGoldBlock: GOLD_BLOCK
    # На каких блоках может появиться золотой блок
    materialList:
      - GRASS_BLOCK
      - SAND
      - RED_SAND
    # Задержка между золотыми блоками (время указывать в секундах 1800 = 30 мин)
    time: 1800
    # Текст голограммы
    hologramLines:
      - "&6&lЗолотой блок"
      - "{endtime}"
    # Установить позицию голограммы
    hologramOffset:
      x: 0.5
      y: 1.7
      z: 0.5
    message:
      posMessage: '&eКоординаты золотого блока x: %s y: %s z: %s'
      endMessage: "&bЗолотой блок закончился"
      youReceived: "&6&lВы получили: &a%s&6&l$"
      startMessage: "&e&lДо золотого блока: %s"
    # Когда выводить сообщение когда будет золотой блок (ниже указан пример)
    reportMessage:
      - 1800 # До золотого блока 00:30:00
      - 600 # До золотого блока 00:10:00
      - 300 # До золотого блока 00:05:00
      - 240
      - 180
      - 120
      - 60
      - 30
      - 10
      - 5
      - 4
      - 3
      - 2
      - 1
  super:
    type: super
    # Мир в котором появляется золотой блок
    world: 'world'
    # Выбрать какая экономика будет использоваться (Vault, PlayerPoint)
    economy: 'Vault'
    # Выбрать будет ли золотой блок появляться рандомно или в определённом месте
    blockMovementType: 'static' # (static - золотой блок будет появляться в определённом месте,
    #random - появляется в радиусе от центра поиска золотого блока)
    # Радиус где может появиться золотой блок
    radius: 2000
    # Максимальная и минимальная высота на которой может появиться золотой блок
    height:
      max: 90
      min: 50
    # Центр поиска золотого блока (если center = 0 то радиус поиска будет от -2000 до 2000)
    center:
      x: 0
      z: 0
    # Позиция золотого блока для static
    posGoldBlock:
      x: 0
      y: 0
      z: 0
    # Сколько времени будет идти золотой блок (время указывать в секундах 300 = 5 мин)
    timeGoldBlock: 300
    # Сколько должно быть игроков на сервере чтобы золотой блок начался
    minPlayers: 3
    # Сколько будет награда за золотой блок
    count: 100
    # Будет ли делиться награда между игроками или нет
    shareCount: true
    # На каком расстоянии от золотого блока игрок будет получать деньги
    radiusPay: 5
    # Какой тип блока будет использоваться
    materialGoldBlock: GOLD_BLOCK
    # На каких блоках может появиться золотой блок
    materialList:
      - GRASS_BLOCK
      - SAND
      - RED_SAND
    # Задержка между золотыми блоками (время указывать в секундах 1800 = 30 мин)
    time: 1800
    # Текст голограммы
    hologramLines:
      - "&6&lЗолотой блок"
      - "{endtime}"
    # Установить позицию голограммы
    hologramOffset:
      x: 0.5
      y: 1.7
      z: 0.5
    message:
      posMessage: '&eКоординаты золотого блока x: %s y: %s z: %s'
      endMessage: "&bЗолотой блок закончился"
      youReceived: "&6&lВы получили: &a%s&6&l$"
      startMessage: "&e&lДо золотого блока: %s"
    # Когда выводить сообщение когда будет золотой блок (ниже указан пример)
    reportMessage:
      - 1800 # До золотого блока 00:30:00
      - 600 # До золотого блока 00:10:00
      - 300 # До золотого блока 00:05:00
      - 240
      - 180
      - 120
      - 60
      - 30
      - 10
      - 5
      - 4
      - 3
      - 2
      - 1


    # Функционал ниже появится в будущем!!!
    # Здесь вы можете настроить бонусы, эффекты и т.д. (если до конца золотого блока остаётся 60 секунд вы можете увеличить количество монет, добавить дебафы)
  # commandManager:
  #   60:
  #     - " give count 100"
  #     - " effect <любой эффект>"
