name: GoldBlock
version: '${project.version}'
main: ru.anime.goldblock.GoldBlock
api-version: '1.16'
commands:
  goldblock:
    aliases:
      - gb
  searchentity:
    aliases:
      - se
  configtest:
    aliases:
      - ct
permissions:
  goldblock.create:
    default: op



