name: GoldBlock
version: '${project.version}'
main: ru.anime.goldblock.Main
api-version: '1.16'
commands:
  goldblock:
    aliases:
      - gb
  searchentity:
    aliases:
      - se
  configtest:
    aliases:
      - ct
permissions:
  goldblock.admin:
    default: op
depend:
  - WorldEdit
  - DecentHolograms
  - WorldGuard
  - Vault


